app: lianheart
stage: prod
component: nextjs
name: website

inputs:
  src:
    hook: npm run build
    dist: ./
    exclude:
      - .env
  region: ap-shanghai
  functionConf:
    name: ${app}-${name}
    runtime: Nodejs12.16
  apigatewayConf:
    protocols:
      - https
    environment: release