app: lianheart
stage: prod
component: nextjs
name: website

inputs:
  src:
    hook: npm run build
    dist: ./
    exclude:
      - .env
      - 'node_modules/**'
      - .git**
      - cloudfunctions
      - cos
      - layer
      - .all-contributorsrc
      - .editorconfig
      - .eslintrc.js
      - .prettierrc
      - .stylelintrc
      - cloudbaserc.json
      - CODEOWNERS
      - LICENSE*
      - netlify.toml
      - README.md
  region: ap-shanghai
  functionConf:
    name: ${app}-${name}
    runtime: Nodejs12.16
    memorySize: 128
  apigatewayConf:
    protocols:
      - https
    environment: release
  layers:
    - name: ${output:${stage}:${app}:layer.name}
      version: ${output:${stage}:${app}:layer.version}
